# Archivo para poder desplegar la app con backend de NodeJS con App Engine
runtime: nodejs14

automatic_scaling:
  min_instances: 5
  max_instances: 100
  min_pending_latency: 3000ms
  max_pending_latency: automatic

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto